[world]
name = "Provable Games"
description = "Test Embeded game"
seed = "asdfasdfasdf"

[namespace]
default = "test"

[writers]
"test" = [
    "test-game_systems",
    "test-config_systems",
]

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x01bfa92665fb815c9ec5f37c562a5c9a06fdf23ce022c1d33d4ac07cef5ad80c"